### ISSUE TITLE
sqd build

### ISSUE THREAD

**Issue by FlipZ3ro** [subsquid-labs/squid-evm-template#52]
sqd build

CLEAN
BUILD
src/main.ts:2:9 - error TS2305: Module '"./model"' has no exported member 'Burn'.

2 import {Burn} from './model'
          ~~~~

**Comment by arapzz** [comment]
have to add model.ts file inside src

// model.ts
export class Burn {
    id: string;
    block: number;
    address: string;
    value: bigint;
    txHash: string;

    constructor({ id, block, address, value, txHash }: Partial<Burn>) {
        this.id = id || '';
        this.block = block || 0;
        this.address = address || '';
        this.value = value || 0n;
        this.txHash = txHash || '';
    }
}

**Comment by arapzz** [comment]
and it was implemented successfully

```
PS C:\Users\user\Desktop\squid\my-new-squid> sqd build  
CLEAN
BUILD
```

**Comment by abernatskiy** [comment]
> sqd build
> 
> CLEAN BUILD src/main.ts:2:9 - error TS2305: Module '"./model"' has no exported member 'Burn'.
> 
> 2 import {Burn} from './model' ~~~~

Weird, the `./src/model/` in the repo's main branch does export `Burn`. It's been a while, closing the issue.
